apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: kznyse0rf-python 
  janus-idp.io/tekton: kznyse0rf-python
  backstage.io/kubernetes-id: kznyse0rf-python
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: kznyse0rf-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml